using System.Collections.Generic;
using System.ComponentModel;

namespace Sys.UI.Localization;

// Arayüz metinleri.
//
// TEK SÖZLÜK, ÇİFT DEĞER. Her anahtarın Türkçe ve İngilizce karşılığı YAN YANA
// duruyor. Ayrı iki sözlük (Tr.cs / En.cs) yazmak daha düzenli görünürdü ama bu
// projede tekrar tekrar aynı hataya düştük: aynı bilginin iki yerde tutulması.
// Renk paletinde, kontrol listesinde, durum kümelerinde hep bu oldu. Böyle
// yazıldığında bir anahtarın bir dilde eksik kalması MÜMKÜN DEĞİL — çift zaten
// bir arada tanımlanıyor.
//
// Çeviri yapılmamış anahtarlar için İngilizce alan Türkçesiyle aynı bırakılabilir;
// bu bilinçli bir ara durumdur ve ekranda boşluk yerine anlaşılır metin görünür.
public sealed class Strings : INotifyPropertyChanged
{
    // XAML'den erişim için tek örnek:
    //   Text="{Binding [Nav.Dashboard], Source={x:Static loc:Strings.Current}}"
    public static Strings Current { get; } = new();

    private Strings() { }

    public event PropertyChangedEventHandler? PropertyChanged;

    // Dil değiştiğinde TÜM bağlamalar tazelensin diye indeksleyicinin tamamı
    // "değişti" olarak duyuruluyor. Anahtar başına ayrı bildirim göndermek
    // yüzlerce olay demek olurdu ve dil nadiren değişen bir ayar.
    internal static void NotifyLanguageChanged()
        => Current.PropertyChanged?.Invoke(Current, new PropertyChangedEventArgs("Item[]"));

    public string this[string key] => T(key);

    // C# tarafı için. Anahtar yoksa anahtarın kendisi köşeli parantezle dönüyor:
    // ekranda boşluk yerine "[Nav.Dashboard]" görünür, yani eksik çeviri sessizce
    // kaybolmaz, test sırasında göze çarpar.
    public static string T(string key)
    {
        if (!Map.TryGetValue(key, out var pair)) return $"[{key}]";
        return LanguageService.IsEnglish ? pair.En : pair.Tr;
    }

    public static string T(string key, params object?[] args) => string.Format(T(key), args);

    // Sözlükte tanımlı tüm anahtarlar — kullanılmayan anahtar taraması için.
    public static IReadOnlyCollection<string> Keys => Map.Keys;

    private static readonly Dictionary<string, (string Tr, string En)> Map = new()
    {
        // --- Sol menü ---
        ["Nav.Dashboard"] = ("Gösterge Paneli", "Dashboard"),
        ["Nav.MyRequests"] = ("Taleplerim", "My Requests"),
        ["Nav.Contracts"] = ("Sözleşmeler", "Contracts"),
        ["Nav.NewRequest"] = ("Yeni Sözleşme Talebi", "New Contract Request"),
        ["Nav.CreateContract"] = ("Sözleşme Yarat", "Create Contract"),
        ["Nav.ViewContracts"] = ("Sözleşmeleri Görüntüle", "View Contracts"),
        ["Nav.FinalCheck"] = ("Son Kontrol (SYB)", "Final Check (CU)"),
        ["Nav.EditContract"] = ("Sözleşme Değiştir", "Amend Contract"),
        ["Nav.Termination"] = ("Sözleşme Fesih", "Terminate Contract"),
        ["Nav.ReportViolation"] = ("İhlal Bildir", "Report Violation"),
        ["Nav.Archive"] = ("Arşiv", "Archive"),
        ["Nav.PendingApprovals"] = ("Onay Bekleyenler", "Pending Approvals"),
        ["Nav.AuditLog"] = ("İşlem Geçmişi", "Audit Log"),
        ["Nav.UserManagement"] = ("Kullanıcı Yönetimi", "User Management"),
        ["Nav.ChangePassword"] = ("Şifre Değiştir", "Change Password"),
        ["Nav.EditRequest"] = ("Talebi Düzenle", "Edit Request"),
        ["Nav.RenewContract"] = ("Sözleşmeyi Yenile", "Renew Contract"),

        // --- Üst çubuk ---
        ["Shell.Logout"] = ("Çıkış Yap", "Sign Out"),
        ["Shell.ThemeToLight"] = ("Açık moda geç", "Switch to light mode"),
        ["Shell.ThemeToDark"] = ("Koyu moda geç", "Switch to dark mode"),
        ["Shell.LanguageToEnglish"] = ("Switch to English", "Switch to English"),
        ["Shell.LanguageToTurkish"] = ("Türkçe'ye geç", "Türkçe'ye geç"),
        ["Shell.Notifications"] = ("Bildirimler", "Notifications"),

        // --- Bildirim paneli ---
        ["Notif.MarkAllRead"] = ("Tümünü okundu işaretle", "Mark all as read"),
        ["Notif.DeleteRead"] = ("Okunanları sil", "Delete read"),
        ["Notif.Empty"] = ("Henüz bildiriminiz yok.", "You have no notifications yet."),
        ["Notif.EmptyHint"] = ("Onay, red ve yaklaşan bitiş uyarıları burada görünür.",
                               "Approvals, rejections and upcoming expiry alerts appear here."),

        // --- Giriş ekranı ---
        ["Login.BrandTitle"] = ("SÖZLEŞME\nYÖNETİM SİSTEMİ", "CONTRACT\nMANAGEMENT SYSTEM"),
        ["Login.Welcome"] = ("Hoş geldiniz", "Welcome"),
        ["Login.Subtitle"] = ("Devam etmek için hesabınıza giriş yapın.", "Sign in to your account to continue."),
        ["Login.Username"] = ("Kullanıcı Adı", "Username"),
        ["Login.UsernamePlaceholder"] = ("kullanici.adi", "user.name"),
        ["Login.Password"] = ("Şifre", "Password"),
        ["Login.CapsLock"] = ("Caps Lock açık", "Caps Lock is on"),
        ["Login.Submit"] = ("Giriş Yap", "Sign In"),
        ["Login.SubmitHint"] = ("Enter tuşuyla da giriş yapabilirsiniz", "You can also press Enter to sign in"),
        ["Login.ForgotPassword"] = ("Şifremi unuttum", "Forgot my password"),
        ["Login.ForgotHint"] = ("Kullanıcı adınızı girin. Sistem yöneticinize bir sıfırlama talebi iletilecek.",
                                "Enter your username. A reset request will be sent to your system administrator."),
        ["Login.ForgotPlaceholder"] = ("Kullanıcı adı", "Username"),
        ["Login.SendRequest"] = ("Talep Gönder", "Send Request"),
        ["Login.UsernameRequired"] = ("Lütfen kullanıcı adınızı girin.", "Please enter your username."),
        ["Login.RequestReceived"] = ("Talebiniz alındı. Sistem yöneticiniz sizinle iletişime geçecek.",
                                     "Your request has been received. Your system administrator will contact you."),
        ["Login.Failed"] = ("Giriş başarısız.", "Sign-in failed."),

        // --- Şifre değiştirme ---
        ["Pwd.ForcedTitle"] = ("Geçici şifrenizi değiştirin", "Change your temporary password"),
        ["Pwd.ForcedSubtitle"] = ("Şu an geçici bir şifre kullanıyorsunuz. Devam etmek için kendi şifrenizi belirleyin.",
                                  "You are using a temporary password. Set your own password to continue."),
        ["Pwd.BackToLogin"] = ("← Giriş ekranına dön", "← Back to sign-in"),
        ["Pwd.Back"] = ("← Geri", "← Back"),
        ["Pwd.BackHint"] = ("Esc tuşuyla da dönebilirsiniz", "You can also press Esc to go back"),
        ["Pwd.Title"] = ("Şifre Değiştir", "Change Password"),
        ["Pwd.Subtitle"] = ("Kimliğinizi doğrulamak için önce mevcut şifrenizi girin.",
                            "Enter your current password first to verify your identity."),
        ["Pwd.Current"] = ("MEVCUT ŞİFRE", "CURRENT PASSWORD"),
        ["Pwd.New"] = ("YENİ ŞİFRE", "NEW PASSWORD"),
        ["Pwd.Repeat"] = ("YENİ ŞİFRE (TEKRAR)", "NEW PASSWORD (REPEAT)"),
        ["Pwd.CapsLock"] = ("Caps Lock açık", "Caps Lock is on"),
        ["Pwd.RulesTitle"] = ("ŞİFRE KURALLARI", "PASSWORD RULES"),
        ["Pwd.RuleMinLength"] = ("En az {0} karakter", "At least {0} characters"),
        ["Pwd.RuleLetter"] = ("En az bir harf", "At least one letter"),
        ["Pwd.RuleDigit"] = ("En az bir rakam", "At least one digit"),
        ["Pwd.RuleMatch"] = ("İki alana da aynı şekilde yazılmalı", "Must be typed identically in both fields"),
        ["Pwd.RuleDifferent"] = ("Mevcut şifrenizden farklı olmalı", "Must differ from your current password"),
        ["Pwd.Saving"] = ("Kaydediliyor...", "Saving..."),
        ["Pwd.Submit"] = ("Şifreyi Değiştir", "Change Password"),
        ["Pwd.CurrentRequired"] = ("Mevcut şifrenizi girin.", "Enter your current password."),
        ["Pwd.RepeatRequired"] = ("Yeni şifreyi tekrar girin.", "Re-enter the new password."),
        ["Pwd.NoMatch"] = ("Şifreler eşleşmiyor.", "Passwords do not match."),
        ["Pwd.FixFields"] = ("Lütfen işaretli alanları düzeltin.", "Please correct the highlighted fields."),
        ["Pwd.ChangeFailed"] = ("Şifre değiştirilemedi.", "Password could not be changed."),
        ["Pwd.Updated"] = ("Şifreniz güncellendi. Bir sonraki girişinizde yeni şifrenizi kullanın.",
                           "Your password has been updated. Use it at your next sign-in."),
        ["Pwd.UnexpectedError"] = ("Şifre değiştirilirken bir hata oluştu: {0}",
                                   "An error occurred while changing the password: {0}"),
        ["Pwd.NoteSession"] = ("Şifreniz değiştikten sonra oturumunuz açık kalır; bir dahaki girişte yeni şifrenizi kullanın.",
                               "Your session stays open after the change; use your new password at your next sign-in."),
        ["Pwd.NoteForgot"] = ("Şifrenizi hatırlamıyorsanız giriş ekranındaki \"Şifremi unuttum\" ile yöneticiye talep gönderebilirsiniz.",
                              "If you cannot remember your password, use \"Forgot my password\" on the sign-in screen to request a reset."),

        // --- Servis hata kodları ---
        //
        // Servis katmanı metin değil kod döndürüyor; çeviri burada yapılıyor.
        // Anahtar adları AppError değerleriyle birebir aynı, böylece kod ile metin
        // arasındaki bağ elle kurulan bir eşleme tablosuna muhtaç kalmıyor.
        ["Err.NotAuthorized"] = ("Bu işlemi yapma yetkiniz yok.", "You are not authorised to perform this action."),
        ["Err.NoAuditLogAccess"] = ("Bu işlem geçmişini görüntüleme yetkiniz yok.", "You are not authorised to view the audit log."),
        ["Err.NoAttachmentAccess"] = ("Bu sözleşmeye dosya ekleme yetkiniz yok.", "You are not authorised to attach files to this contract."),
        ["Err.CannotEditRequest"] = ("Bu talebi düzenleme yetkiniz yok.", "You are not authorised to edit this request."),
        ["Err.CannotDisableOwnAccount"] = ("Kendi hesabınızı devre dışı bırakamazsınız.", "You cannot disable your own account."),
        ["Err.ApprovalNotAvailableAtThisStage"] = ("Bu aşamada onay/red işlemi yapılamaz.",
                                                   "Approval or rejection is not available at this stage."),
        ["Err.RequestAlreadyProcessed"] = ("Bu talep artık düzenlenemez, işlem görmüş.",
                                           "This request can no longer be edited; it has already been processed."),
        ["Err.RequestClosedByRejection"] = ("Bu talep reddedilerek kapatılmıştır, yeniden gönderilemez. Gerekiyorsa yeni bir talep oluşturun.",
                                            "This request was rejected and closed; it cannot be resubmitted. Create a new request if needed."),
        ["Err.RequestNoLongerPending"] = ("Bu talep sözleşmeye dönüştürülemez; artık bekleyen bir talep değil.",
                                          "This request cannot be converted into a contract; it is no longer pending."),
        ["Err.OnlyUnconvertedRequestsCanBeRejected"] = ("Yalnızca henüz sözleşmeye dönüşmemiş talepler reddedilebilir.",
                                                        "Only requests that have not yet become contracts can be rejected."),
        ["Err.ContractNotLive"] = ("Bu sözleşme için {0} işlemi yapılamaz: sözleşme yürürlükte değil.",
                                   "The {0} action is not available: this contract is not in force."),
        ["Err.PendingEditExists"] = ("Bu sözleşmede onay bekleyen bir düzenleme talebi var; sonuçlanmadan yeni işlem yapılamaz.",
                                     "This contract has an amendment awaiting approval; no new action can be taken until it is resolved."),
        ["Err.PendingTerminationExists"] = ("Bu sözleşmede onay bekleyen bir fesih talebi var; sonuçlanmadan yeni işlem yapılamaz.",
                                            "This contract has a termination awaiting approval; no new action can be taken until it is resolved."),
        ["Err.ViolationAlreadyResolved"] = ("Bu ihlal zaten giderildi olarak işaretlenmiş.", "This violation is already marked as resolved."),
        ["Err.RejectionNoteRequired"] = ("Reddetme işlemi için bir gerekçe girilmelidir.", "A reason must be given when rejecting."),
        ["Err.ResolutionNoteRequired"] = ("İhlalin nasıl giderildiği yazılmalıdır.", "You must describe how the violation was resolved."),
        ["Err.DatesRequired"] = ("Sözleşmenin başlangıç ve bitiş tarihi girilmelidir.", "The contract start and end dates are required."),
        ["Err.EndDateBeforeStart"] = ("Bitiş tarihi, başlangıç tarihinden sonra olmalıdır.", "The end date must be later than the start date."),
        ["Err.AtLeastOneItemRequired"] = ("Sözleşmede en az bir bedel kalemi bulunmalıdır.", "The contract must contain at least one line item."),
        ["Err.UserNotFound"] = ("Kullanıcı bulunamadı.", "User not found."),
        ["Err.InvalidCredentials"] = ("Kullanıcı adı veya şifre hatalı.", "Incorrect username or password."),
        ["Err.AccountDisabled"] = ("Bu hesap devre dışı bırakılmış. Yöneticinizle iletişime geçin.",
                                   "This account has been disabled. Contact your administrator."),
        ["Err.AccountLocked"] = ("Hesap kilitli. {0} sonrasında tekrar deneyin.", "Account locked. Try again after {0}."),
        ["Err.TooManyAttempts"] = ("Çok fazla hatalı deneme. Hesap 15 dakika kilitlendi.",
                                   "Too many failed attempts. The account is locked for 15 minutes."),
        ["Err.NewPasswordSameAsCurrent"] = ("Yeni şifre, mevcut şifreyle aynı olamaz.", "The new password cannot be the same as the current one."),
        ["Err.CurrentPasswordIncorrect"] = ("Mevcut şifreniz hatalı.", "Your current password is incorrect."),
        ["Err.PasswordEmpty"] = ("Şifre boş olamaz.", "The password cannot be empty."),
        ["Err.PasswordTooShort"] = ("Şifre en az {0} karakter olmalıdır.", "The password must be at least {0} characters."),
        ["Err.PasswordNeedsLetter"] = ("Şifre en az bir harf içermelidir.", "The password must contain at least one letter."),
        ["Err.PasswordNeedsDigit"] = ("Şifre en az bir rakam içermelidir.", "The password must contain at least one digit."),

        // Hata metinlerinde geçen işlem adları
        ["Op.Edit"] = ("düzenleme", "amendment"),
        ["Op.Violation"] = ("ihlal bildirimi", "violation report"),
        ["Op.Termination"] = ("fesih", "termination"),

        // --- Ortak ---
        ["Common.Loading"] = ("Yükleniyor...", "Loading..."),
        ["Common.Refresh"] = ("Yenile", "Refresh"),
        ["Common.RefreshHint"] = ("Listeyi yenile", "Refresh the list"),
        ["Common.Detail"] = ("Detay", "Details"),
        ["Common.Edit"] = ("Düzenle", "Edit"),
        ["Common.Excel"] = ("Excel", "Excel"),
        ["Common.ExcelHint"] = ("Filtrelenmiş listeyi Excel dosyası olarak kaydeder",
                                "Saves the filtered list as an Excel file"),
        ["Common.Previous"] = ("‹ Önceki", "‹ Previous"),
        ["Common.Next"] = ("Sonraki ›", "Next ›"),
        ["Common.ClearFilters"] = ("Filtreleri temizle", "Clear filters"),
        ["Common.All"] = ("Tümü", "All"),

        // --- Durum adları ---
        ["Status.Live"] = ("Yürürlükte", "In Force"),
        ["Status.PendingApproval"] = ("Onay Bekliyor", "Awaiting Approval"),
        ["Status.Warning"] = ("Uyarı", "Expiring"),
        ["Status.Violation"] = ("İhlal", "Violation"),
        ["Status.Rejected"] = ("Reddedilen", "Rejected"),

        // --- Gösterge paneli ---
        ["Dash.LiveSubtitle"] = ("aktif, bitişi yaklaşan ve ihlalli", "active, expiring and in violation"),
        ["Dash.PendingSubtitle"] = ("süreçte bekleyen", "waiting in the approval chain"),
        ["Dash.ExpiryWarning"] = ("Bitiş Uyarısı", "Expiry Warning"),
        ["Dash.ExpiryWarningSubtitle"] = ("30 günden az kaldı", "fewer than 30 days left"),
        ["Dash.OpenViolations"] = ("Açık İhlal", "Open Violations"),
        ["Dash.PendingWork"] = ("SİZİ BEKLEYEN İŞLER", "WAITING ON YOU"),
        ["Dash.TotalValue"] = ("TOPLAM SÖZLEŞME DEĞERİ", "TOTAL CONTRACT VALUE"),
        ["Dash.NoCurrencyConversion"] = ("Kur dönüşümü yapılmaz; her para birimi ayrı gösterilir.",
                                         "No currency conversion is applied; each currency is listed separately."),
        ["Dash.TypeBreakdown"] = ("YÜRÜRLÜKTEKİ SÖZLEŞMELER — TÜR DAĞILIMI", "CONTRACTS IN FORCE — BY TYPE"),
        ["Dash.UpcomingEndings"] = ("YAKLAŞAN BİTİŞLER (30 GÜN İÇİNDE)", "UPCOMING EXPIRIES (WITHIN 30 DAYS)"),
        ["Dash.NoUpcoming"] = ("Önümüzdeki 30 gün içinde sona erecek sözleşme yok.",
                               "No contracts are due to expire in the next 30 days."),
        ["Dash.NoLiveContracts"] = ("Yürürlükteki sözleşme yok.", "No contracts are currently in force."),
        ["Dash.RecentActivity"] = ("SON AKTİVİTELER", "RECENT ACTIVITY"),
        ["Dash.ThisMonth"] = ("BU AY", "THIS MONTH"),
        ["Dash.NewRequest"] = ("Yeni talep", "New requests"),
        ["Dash.Activated"] = ("Yürürlüğe giren", "Came into force"),
        ["Dash.Terminated"] = ("Feshedilen", "Terminated"),
        ["Dash.Renewed"] = ("Yenilendi", "Renewed"),

        // --- Sözleşme listesi ---
        ["List.SearchPlaceholder"] = ("Başlık, firma veya sözleşme numarasına göre ara...",
                                      "Search by title, company or contract number..."),
        ["List.TypeFilterHint"] = ("Sözleşme türüne göre filtrele", "Filter by contract type"),
        ["List.NoMatch"] = ("Bu filtrelerle eşleşen sözleşme bulunamadı.", "No contracts match these filters."),
        ["List.ColType"] = ("TÜR", "TYPE"),
        ["List.ColAmount"] = ("BEDEL", "AMOUNT"),
        ["List.ColRemaining"] = ("KALAN", "REMAINING"),
        ["List.GoToFinalCheck"] = ("Son Kontrol'e Git", "Go to Final Check"),
        ["List.CreateContract"] = ("Sözleşme Yarat", "Create Contract"),

        // --- Sözleşme kartı ---
        ["Card.StatusRequest"] = ("Talep", "Request"),
        ["Card.StatusExpiring"] = ("Bitiş Yaklaşıyor", "Expiring Soon"),
        ["Card.StatusInViolation"] = ("İhlal Mevcut", "In Violation"),
        ["Card.StatusCompleted"] = ("Tamamlandı", "Completed"),
        ["Card.StatusTerminated"] = ("Feshedildi", "Terminated"),
        ["Card.StatusRejected"] = ("Reddedildi", "Rejected"),
        ["Card.BadgeReturned"] = ("İade Edildi", "Returned"),
        ["Card.BadgeFromManagement"] = ("Yönetimden Döndü", "Returned by Management"),
        ["Card.BadgeWithdrawn"] = ("Geri Çekildi", "Withdrawn"),
        ["Card.StageFinalCheck"] = ("SYB Son Kontrol", "Final Check"),
        ["Card.StageManagement"] = ("YK Onayı", "Board Approval"),
        ["Card.RejectRequest"] = ("Talebi Reddet", "Reject Request"),
        ["Card.WithdrawRequest"] = ("Talebi Geri Çek", "Withdraw Request"),
        ["Card.NoteClosed"] = ("Talep reddedildi ve kapatıldı. Gerekçe: {0}",
                               "The request was rejected and closed. Reason: {0}"),
        ["Card.NoteBackToFinalCheck"] = ("Yönetim onayından döndü — Son Kontrol tekrar yapılmalı. Gerekçe: {0}",
                                         "Returned by management — the final check must be repeated. Reason: {0}"),
        ["Card.NoteBackInfo"] = ("Yönetim onayından döndü; SYB yeniden inceliyor. Gerekçe: {0}",
                                 "Returned by management; the contracts unit is reviewing it again. Reason: {0}"),
        ["Card.NoteFixAndResend"] = ("Yönetim onayından döndü — düzeltip yeniden gönderin. Gerekçe: {0}",
                                     "Returned by management — correct it and resubmit. Reason: {0}"),
        ["Card.NoteWithdrawn"] = ("Talebi geri çektiniz; düzeltip yeniden gönderebilirsiniz. Gerekçe: {0}",
                                  "You withdrew this request; you can correct it and resubmit. Reason: {0}"),
        ["Card.NoteReturned"] = ("Düzeltilmek üzere iade edildi. Gerekçe: {0}",
                                 "Returned for correction. Reason: {0}"),
        ["Card.NoReason"] = ("belirtilmemiş", "not stated"),
        ["Card.NoDate"] = ("Tarih girilmemiş", "No date entered"),
        ["Card.EndsOn"] = ("Bitiş: ", "Ends: "),
        ["Card.RejectedOn"] = ("Reddedildi: ", "Rejected: "),
        ["Card.StageTermination"] = ("Fesih", "Termination"),
        ["Card.DaysLeft"] = ("{0} gün kaldı", "{0} days left"),

        // --- Panel: üretilen metinler ---
        ["Dash.NoOpenViolations"] = ("açık ihlal yok", "no open violations"),
        ["Dash.ViolationsAcross"] = ("{0} sözleşmede, giderilmeyi bekliyor",
                                     "across {0} contract(s), awaiting resolution"),
        ["Dash.ContractCount"] = ("{0} sözleşme", "{0} contract(s)"),
        ["Dash.TypeRowTooltip"] = ("Bu türdeki sözleşmeleri listele", "List contracts of this type"),
        ["Dash.EndsToday"] = ("Bugün sona eriyor", "Ends today"),
        ["Dash.Ended"] = ("Sona erdi", "Ended"),
        ["Dash.ArrivedToday"] = ("Bugün geldi", "Arrived today"),
        ["Dash.OldestWaitingOne"] = ("En eskisi 1 gündür bekliyor", "The oldest has waited 1 day"),
        ["Dash.OldestWaiting"] = ("En eskisi {0} gündür bekliyor", "The oldest has waited {0} days"),
        ["Dash.LoadFailed"] = ("Panel yüklenemedi: {0}", "The dashboard could not be loaded: {0}"),
        ["Dash.GoodMorning"] = ("Günaydın", "Good morning"),
        ["Dash.GoodDay"] = ("İyi günler", "Good afternoon"),
        ["Dash.GoodEvening"] = ("İyi akşamlar", "Good evening"),
        ["Dash.GoodNight"] = ("İyi geceler", "Good night"),

        // --- Sizi bekleyen işler (servis anahtarları) ---
        ["Work.RequestsToConvert"] = ("Sözleşmeye dönüştürülecek talepler", "Requests to convert into contracts"),
        ["Work.RequestsToConvertSub"] = ("Onaylanmış talepler sözleşme oluşturulmayı bekliyor",
                                         "Approved requests are waiting for a contract to be created"),
        ["Work.AwaitingYourFinalCheck"] = ("Son kontrolünüzde bekleyenler", "Awaiting your final check"),
        ["Work.AwaitingYourFinalCheckSub"] = ("SYB onayı verilmemiş sözleşmeler", "Contracts not yet approved by the contracts unit"),
        ["Work.AwaitingYourApproval"] = ("Onayınızda bekleyenler", "Awaiting your approval"),
        ["Work.AwaitingYourApprovalSub"] = ("Yönetim onayı verilmemiş sözleşmeler", "Contracts not yet approved by management"),
        ["Work.RequestsNeedingFix"] = ("Düzeltme bekleyen talepleriniz", "Your requests awaiting correction"),
        ["Work.RequestsNeedingFixSub"] = ("Reddedilmiş, yeniden gönderilmesi gereken talepler",
                                          "Rejected requests that need to be resubmitted"),

        // --- Sözleşme alan adları (birden fazla ekranda ortak) ---
        ["Field.Scope"] = ("Kapsam", "Scope"),
        ["Field.Items"] = ("Kalemler", "Line Items"),
        ["Field.Files"] = ("Dosyalar", "Files"),
        ["Field.Description"] = ("AÇIKLAMA", "DESCRIPTION"),
        ["Field.Quantity"] = ("MİKTAR", "QUANTITY"),
        ["Field.UnitPrice"] = ("BİRİM FİYAT", "UNIT PRICE"),
        ["Field.LineTotal"] = ("TUTAR", "AMOUNT"),
        ["Field.TotalAmount"] = ("TOPLAM BEDEL", "TOTAL AMOUNT"),
        ["Field.Type"] = ("TÜR", "TYPE"),
        ["Field.TaxNo"] = ("VERGİ NO", "TAX NO"),
        ["Field.SapCode"] = ("SAP CARİ KODU", "SAP ACCOUNT CODE"),
        ["Field.CompanyType"] = ("FİRMA TÜRÜ", "COMPANY TYPE"),
        ["Field.StartDate"] = ("BAŞLANGIÇ", "START"),
        ["Field.EndDate"] = ("BİTİŞ", "END"),
        ["Field.PaymentPeriod"] = ("ÖDEME PERİYODU", "PAYMENT PERIOD"),
        ["Field.Requester"] = ("TALEP EDEN", "REQUESTED BY"),
        ["Field.RequestRefNo"] = ("TALEP REFERANS NO", "REQUEST REF. NO"),
        ["Field.Note"] = ("Not", "Note"),
        ["Field.Open"] = ("Aç", "Open"),

        // --- Onay kuyruğu ---
        ["Queue.Queue"] = ("KUYRUK", "QUEUE"),
        ["Queue.Decision"] = ("KARAR", "DECISION"),
        ["Queue.Empty"] = ("Onayınızı bekleyen sözleşme yok.", "No contracts are awaiting your approval."),
        ["Queue.PickFromQueue"] = ("İncelemek istediğiniz sözleşmeyi soldaki kuyruktan seçin.",
                                   "Choose a contract from the queue on the left to review it."),
        ["Queue.NotePlaceholder"] = ("Reddederken gerekçe zorunludur.", "A reason is required when rejecting."),
        ["Queue.ChecklistRequired"] = ("Onaylamak için kontrol listesindeki tüm maddeleri işaretleyin.",
                                       "Tick every item on the checklist before approving."),
        ["Queue.ViolationRecord"] = ("İhlal Sicili", "Violation Record"),
        ["Queue.BackToContracts"] = ("← Sözleşmeler", "← Contracts"),
        ["Queue.IsRevision"] = ("ℹ BU BİR DEĞİŞİKLİK (REVİZYON) ONAYIDIR", "ℹ THIS IS AN AMENDMENT APPROVAL"),
        ["Queue.IsTermination"] = ("⚠ BU BİR FESİH TALEBİDİR", "⚠ THIS IS A TERMINATION REQUEST"),
        ["Queue.WasRejected"] = ("⟲ BU SÖZLEŞME DAHA ÖNCE REDDEDİLDİ", "⟲ THIS CONTRACT WAS REJECTED BEFORE"),
        ["Queue.WasRejectedShort"] = ("⟲ Daha önce reddedildi", "⟲ Rejected before"),

        // --- Liste: üretilen metinler ---
        ["List.AllTypes"] = ("Tüm türler", "All types"),
        ["List.PageInfo"] = ("Sayfa {0} / {1}  ·  Toplam {2} kayıt", "Page {0} of {1}  ·  {2} records"),
        ["List.LoadFailed"] = ("Sözleşmeler yüklenirken bir hata oluştu: {0}",
                               "An error occurred while loading contracts: {0}"),
        ["List.RejectFailed"] = ("Talep reddedilirken bir hata oluştu: {0}",
                                 "An error occurred while rejecting the request: {0}"),
        ["List.ExportFailed"] = ("Excel'e aktarılamadı: {0}", "Export to Excel failed: {0}"),
        ["List.ExportCapped"] = ("Aktarma {0} kayıtla sınırlandı. Tümünü almak için filtreyi daraltıp tekrar deneyin.",
                                 "The export was capped at {0} records. Narrow the filter and try again to get them all."),
        ["List.ExportName"] = ("Sözleşme listesi", "Contract list"),

        // --- Onay kuyruğu: üretilen metinler ---
        ["Queue.ConfirmApproveTermination"] = ("Evet, Feshi Onayla", "Yes, Approve Termination"),
        ["Queue.ConfirmApproveEdit"] = ("Evet, Değişikliği Onayla", "Yes, Approve Amendment"),
        ["Queue.ConfirmApprove"] = ("Evet, Onayla", "Yes, Approve"),
        ["Queue.ConfirmRejectTermination"] = ("Evet, Feshi Reddet", "Yes, Reject Termination"),
        ["Queue.ConfirmRejectEdit"] = ("Evet, Değişikliği Reddet", "Yes, Reject Amendment"),
        ["Queue.ConfirmReject"] = ("Evet, Reddet", "Yes, Reject"),
        ["Queue.ChecklistTitleTermination"] = ("FESİH SON KONTROLÜ", "TERMINATION FINAL CHECK"),
        ["Queue.ChecklistTitleEdit"] = ("DEĞİŞİKLİK SON KONTROLÜ", "AMENDMENT FINAL CHECK"),
        ["Queue.ChecklistTitleContract"] = ("SÖZLEŞME SON KONTROLÜ", "CONTRACT FINAL CHECK"),
        ["Queue.LoadListFailed"] = ("Liste yüklenirken bir hata oluştu: {0}", "An error occurred while loading the list: {0}"),
        ["Queue.ContractLoadFailed"] = ("Sözleşme yüklenemedi.", "The contract could not be loaded."),
        ["Queue.DetailLoadFailed"] = ("Sözleşme detayı yüklenirken bir hata oluştu: {0}",
                                      "An error occurred while loading the contract details: {0}"),
        ["Queue.SelectFirst"] = ("Önce listeden bir sözleşme seçin.", "Select a contract from the list first."),
        ["Queue.NoteRequired"] = ("Reddetme işlemi için bir gerekçe girmelisiniz.", "You must give a reason when rejecting."),
        ["Queue.FileOpenFailed"] = ("Dosya açılamadı: {0}", "The file could not be opened: {0}"),
        ["Queue.PrevRejectionInfo"] = ("Reddeden adım: {0}\nTarih: {1}\nGerekçe: {2}",
                                       "Rejected at: {0}\nDate: {1}\nReason: {2}"),
        ["Queue.TerminationInfo"] = ("Fesih Türü: {0}\nFesih Tarihi: {1}\nGerekçe: {2}\nTazminat: {3}",
                                     "Termination Type: {0}\nTermination Date: {1}\nReason: {2}\nCompensation: {3}"),
        ["Queue.RevisionInfo"] = ("Değişiklik Türü: {0}\nGerekçe: {1}\nÖnceki Bedel: {2}",
                                  "Amendment Type: {0}\nReason: {1}\nPrevious Amount: {2}"),
        ["Queue.NoCompensation"] = ("Yok", "None"),
        ["Queue.Approved"] = ("onaylandı", "approved"),
        ["Queue.Rejected"] = ("reddedildi", "rejected"),
        ["Queue.DecisionSaved"] = ("\"{0}\" {1}.", "\"{0}\" was {1}."),
        ["Queue.DecisionSavedEmpty"] = ("\"{0}\" {1}. Kuyrukta bekleyen başka sözleşme kalmadı.",
                                        "\"{0}\" was {1}. No contracts remain in the queue."),
        ["Queue.DecisionSavedNext"] = ("\"{0}\" {1}. Sıradaki sözleşme açıldı: {2}",
                                       "\"{0}\" was {1}. Opened the next contract: {2}"),

        // --- Son kontrol listesi maddeleri ---
        ["Check.Term1"] = ("Fesih türü ve gerekçesi sözleşme hükümleriyle uyumlu",
                           "Termination type and reason are consistent with the contract terms"),
        ["Check.Term2"] = ("Fesih tarihi doğru; kalan süre ve yükümlülükler değerlendirildi",
                           "Termination date is correct; remaining term and obligations were considered"),
        ["Check.Term3"] = ("Tazminat tutarı ve yönü (ödenecek / alınacak) doğru",
                           "Compensation amount and direction (payable / receivable) are correct"),
        ["Check.Term4"] = ("Fesih bildirimi veya yazışma belgesi eklendi",
                           "The termination notice or correspondence has been attached"),
        ["Check.Term5"] = ("Firmayla açık bakiye ve devam eden ihlal durumu kontrol edildi",
                           "Outstanding balance and open violations with the company were checked"),
        ["Check.New1"] = ("Kapsam, talebin konusuyla örtüşüyor", "The scope matches the subject of the request"),
        ["Check.New2"] = ("Bedel kalemleri ve toplam tutar doğru", "Line items and the total amount are correct"),
        ["Check.New3"] = ("Firma bilgileri doğru (Vergi No, SAP Cari Kodu)",
                          "Company details are correct (tax number, SAP account code)"),
        ["Check.New4"] = ("Başlangıç/Bitiş tarihleri ve ödeme periyodu doğru",
                          "Start/end dates and the payment period are correct"),
        ["Check.New5"] = ("Sözleşme dosyası yüklendi; ek ve teminat belgeleri tam",
                          "The contract file is uploaded; annexes and guarantee documents are complete"),
        ["Check.Edit1"] = ("Değişiklik türü ve gerekçesi açık ve yeterli", "Amendment type and reason are clear and sufficient"),
        ["Check.Edit2"] = ("Yeni değerler, önceki değerlerle karşılaştırıldı", "New values were compared with the previous ones"),
        ["Check.Edit3"] = ("Bedel değişikliği bütçe açısından uygun", "The change in amount is acceptable for the budget"),
        ["Check.Edit4"] = ("Yeni tarih / ödeme koşulları sözleşmeyle tutarlı",
                           "New dates and payment terms are consistent with the contract"),
        ["Check.Edit5"] = ("Değişikliği destekleyen belge (zeyilname, yazışma) eklendi",
                           "Supporting document (addendum, correspondence) has been attached"),

        // --- Onay/red penceresi ---
        ["Confirm.Title"] = ("Onay", "Confirm"),
        ["Confirm.Cancel"] = ("Vazgeç", "Cancel"),
        ["Confirm.Default"] = ("Evet, Devam Et", "Yes, Continue"),
        ["Queue.ApproveAndNext"] = ("Onayla ve Sıradakine Geç", "Approve and Go to Next"),
        ["Queue.Approve"] = ("Onayla", "Approve"),
        ["Queue.RejectAndNext"] = ("Reddet ve Sıradakine Geç", "Reject and Go to Next"),
        ["Queue.Reject"] = ("Reddet", "Reject"),
        ["Queue.ApproveAskGeneric"] = ("Bu kararı onaylamak istediğinizden emin misiniz?",
                                       "Are you sure you want to approve this decision?"),
        ["Queue.RejectAskGeneric"] = ("Bu kararı reddetmek istediğinizden emin misiniz?",
                                      "Are you sure you want to reject this decision?"),
        ["Queue.ApproveAskTermination"] = ("Bu fesih talebini onaylamak istediğinizden emin misiniz? {0}",
                                           "Are you sure you want to approve this termination request? {0}"),
        ["Queue.ApproveAskEdit"] = ("Bu değişiklik talebini onaylamak istediğinizden emin misiniz? {0}",
                                    "Are you sure you want to approve this amendment request? {0}"),
        ["Queue.ApproveAskContract"] = ("Bu sözleşmeyi onaylamak istediğinizden emin misiniz? {0}",
                                        "Are you sure you want to approve this contract? {0}"),
        ["Queue.SendsToManagement"] = ("Talep yönetim onayına gönderilecek.", "The request will be sent for management approval."),
        ["Queue.WillTerminate"] = ("Sözleşme feshedilecek ve arşive alınacak.", "The contract will be terminated and archived."),
        ["Queue.EditBecomesPermanent"] = ("Yeni değerler sözleşmede kalıcı olacak.", "The new values will become permanent."),
        ["Queue.ContractToManagement"] = ("Sözleşme yönetim onayına gönderilecek.", "The contract will be sent for management approval."),
        ["Queue.ContractComesIntoForce"] = ("Sözleşme yürürlüğe girecek.", "The contract will come into force."),
        ["Queue.RejectAskTermination"] = ("Bu fesih talebini reddetmek istediğinizden emin misiniz? Sözleşme feshedilmeyecek, yürürlükte kalmaya devam edecek.",
                                          "Are you sure you want to reject this termination request? The contract will not be terminated and will stay in force."),
        ["Queue.RejectAskEdit"] = ("Bu değişiklik talebini reddetmek istediğinizden emin misiniz? Sözleşme değişiklik öncesi değerlerine döndürülecek.",
                                   "Are you sure you want to reject this amendment request? The contract will revert to its previous values."),
        ["Queue.RejectAskContract"] = ("Bu sözleşmeyi reddetmek istediğinizden emin misiniz? {0}",
                                       "Are you sure you want to reject this contract? {0}"),
        ["Queue.ReturnsToOwner"] = ("Talep, düzeltilmek üzere sahibine geri gönderilecek.",
                                    "The request will be returned to its owner for correction."),
        ["Queue.ReturnsToFinalCheck"] = ("Sözleşme SYB son kontrolüne geri gönderilecek.",
                                         "The contract will be returned to the final check."),

        // --- Diğer onay pencereleri ---
        ["Confirm.DeleteFile"] = ("\"{0}\" dosyasını silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
                                  "Are you sure you want to delete \"{0}\"? This cannot be undone."),
        ["Confirm.DeleteFileButton"] = ("Evet, Sil", "Yes, Delete"),
        ["Confirm.TerminationAsk"] = ("\"{0}\" sözleşmesi için fesih talebi gönderilecek.\n\nTalep, SYB son kontrolü ve Yönetim (YK) onayından geçtikten sonra sözleşme feshedilir ve arşive alınır. Devam etmek istiyor musunuz?",
                                      "A termination request will be submitted for \"{0}\".\n\nOnce the request passes the final check and management approval, the contract is terminated and archived. Do you want to continue?"),
        ["Confirm.TerminationButton"] = ("Evet, Fesih Talebini Gönder", "Yes, Submit Termination Request"),
        ["Confirm.ViolationAsk"] = ("\"{0}\" sözleşmesi için ihlal bildirilecek.\n\nSözleşme hemen \"İhlal Mevcut\" durumuna geçecek ve kayıt sözleşmenin geçmişinde kalıcı olacak. Devam etmek istiyor musunuz?",
                                    "A violation will be reported for \"{0}\".\n\nThe contract moves to \"In Violation\" immediately and the record stays permanently in its history. Do you want to continue?"),
        ["Confirm.ViolationButton"] = ("Evet, İhlali Bildir", "Yes, Report Violation"),

        // --- Arşiv ---
        ["Arc.Subtitle"] = ("Süresi dolan, feshedilen ve reddedilen kayıtlar — salt okunur",
                            "Expired, terminated and rejected records — read only"),
        ["Arc.SearchPlaceholder"] = ("Başlık, firma veya no ile ara...", "Search by title, company or number..."),
        ["Arc.Expired"] = ("Süresi Doldu", "Expired"),
        ["Arc.NoMatch"] = ("Bu filtrelerle eşleşen arşiv kaydı yok.", "No archived records match these filters."),
        ["Arc.PickToSeeDetail"] = ("Detayları görmek için soldan bir sözleşme seçin.",
                                   "Select a contract on the left to see its details."),
        ["Arc.ExcelHint"] = ("Filtrelenmiş arşiv listesini Excel dosyası olarak kaydeder",
                             "Saves the filtered archive list as an Excel file"),
        ["Arc.TerminationInfo"] = ("FESİH BİLGİSİ", "TERMINATION DETAILS"),
        ["Arc.RejectionInfo"] = ("RED BİLGİSİ", "REJECTION DETAILS"),

        // --- Sözleşme künyesi (arşiv + detay ortak) ---
        ["Doc.Company"] = ("FİRMA", "COMPANY"),
        ["Doc.Department"] = ("DEPARTMAN", "DEPARTMENT"),
        ["Doc.SapCode"] = ("SAP CARİ", "SAP ACCOUNT"),
        ["Doc.Items"] = ("KALEMLER", "LINE ITEMS"),
        ["Doc.Files"] = ("DOSYALAR", "FILES"),
        ["Doc.ProcessSteps"] = ("SÜREÇ ADIMLARI", "PROCESS STEPS"),
        ["Doc.Description"] = ("Açıklama", "Description"),
        ["Doc.Quantity"] = ("Miktar", "Quantity"),
        ["Doc.UnitPrice"] = ("Birim Fiyat", "Unit Price"),
        ["Doc.LineTotal"] = ("Tutar", "Amount"),
        ["Doc.Print"] = ("Yazdır", "Print"),
        ["Doc.PrintHint"] = ("Sözleşme künyesini varsayılan yazıcıya gönderir",
                             "Sends the contract summary to the default printer"),
        ["Doc.SavePdf"] = ("PDF Kaydet", "Save PDF"),
        ["Doc.SavePdfHint"] = ("Sözleşme künyesini PDF dosyası olarak kaydeder",
                               "Saves the contract summary as a PDF file"),
        ["Doc.Renew"] = ("Sözleşmeyi Yenile", "Renew Contract"),
        ["Doc.RenewHint"] = ("Bu sözleşmenin bilgileriyle yeni dönem talebi oluşturur",
                             "Creates a new-period request from this contract's details"),

        // --- İşlem geçmişi ---
        ["Audit.UnknownUser"] = ("Kullanıcı #{0}", "User #{0}"),
        ["Audit.Date"] = ("TARİH", "DATE"),
        ["Audit.User"] = ("KULLANICI", "USER"),
        ["Audit.Action"] = ("İŞLEM", "ACTION"),
        ["Audit.ActionType"] = ("İŞLEM TÜRÜ", "ACTION TYPE"),
        ["Audit.Detail"] = ("AYRINTI", "DETAIL"),
        ["Audit.From"] = ("BAŞLANGIÇ", "FROM"),
        ["Audit.To"] = ("BİTİŞ", "TO"),
        ["Audit.Clear"] = ("Temizle", "Clear"),
        ["Audit.NoMatch"] = ("Bu filtrelerle eşleşen işlem kaydı bulunamadı.", "No audit records match these filters."),
        ["Audit.ExcelHint"] = ("Filtrelenmiş kayıtları Excel dosyası olarak kaydeder",
                               "Saves the filtered records as an Excel file"),

        // --- Arşiv / işlem geçmişi: üretilen metinler ---
        ["Arc.PageInfo"] = ("{0} / {1}  ·  {2} kayıt", "{0} / {1}  ·  {2} records"),
        ["Arc.LoadFailed"] = ("Arşiv yüklenirken bir hata oluştu: {0}", "An error occurred while loading the archive: {0}"),
        ["Arc.NoAccess"] = ("Bu sözleşmeyi görüntüleme yetkiniz yok.", "You are not authorised to view this contract."),
        ["Arc.DetailLoadFailed"] = ("Sözleşme detayı yüklenirken bir hata oluştu: {0}",
                                    "An error occurred while loading the contract details: {0}"),
        ["Arc.PdfFailed"] = ("PDF oluşturulamadı: {0}", "The PDF could not be created: {0}"),
        ["Arc.PrintFailed"] = ("Yazdırma başlatılamadı: {0}", "Printing could not be started: {0}"),
        ["Arc.FileOpenFailed"] = ("Dosya açılamadı: {0}", "The file could not be opened: {0}"),
        ["Arc.ExportName"] = ("Arşiv listesi", "Archive list"),
        ["Arc.TerminationDetail"] = ("Fesih Türü: {0}\nFesih Tarihi: {1}\nGerekçe: {2}",
                                     "Termination Type: {0}\nTermination Date: {1}\nReason: {2}"),
        ["Arc.RejectionDetail"] = ("Red Tarihi: {0}\nGerekçe: {1}\nBu talep sözleşmeye dönüşmeden kapatılmıştır.",
                                   "Rejection Date: {0}\nReason: {1}\nThis request was closed before becoming a contract."),
        ["Audit.AllActions"] = ("Tüm işlemler", "All actions"),
        ["Audit.PageInfo"] = ("Sayfa {0} / {1} ({2} kayıt)", "Page {0} of {1} ({2} records)"),
        ["Audit.UserListFailed"] = ("Kullanıcı listesi yüklenirken bir hata oluştu: {0}",
                                    "An error occurred while loading the user list: {0}"),
        ["Audit.LoadFailed"] = ("İşlem geçmişi yüklenirken bir hata oluştu: {0}",
                                "An error occurred while loading the audit log: {0}"),
        ["Audit.ExportName"] = ("İşlem geçmişi", "Audit log"),
        ["Audit.ExportCapped"] = ("Aktarma {0} kayıtla sınırlandı. Tümünü almak için tarih aralığını daraltıp tekrar deneyin.",
                                  "The export was capped at {0} records. Narrow the date range and try again to get them all."),

        // --- Denetim kaydı işlem adları ---
        ["Act.TalepOluşturuldu"] = ("Talep Oluşturuldu", "Request Created"),
        ["Act.TalepGüncellendi"] = ("Talep Güncellendi", "Request Updated"),
        ["Act.TalepİadeEdildi"] = ("Talep İade Edildi", "Request Returned"),
        ["Act.TalepGeriÇekildi"] = ("Talep Geri Çekildi", "Request Withdrawn"),
        ["Act.TalepReddedildi"] = ("Talep Reddedildi (Kapatıldı)", "Request Rejected (Closed)"),
        ["Act.SözleşmeOluşturuldu"] = ("Sözleşme Oluşturuldu", "Contract Created"),
        ["Act.SözleşmeDüzenlendi"] = ("Sözleşme Düzenlendi", "Contract Amended"),
        ["Act.FesihTalebiOluşturuldu"] = ("Fesih Talebi Oluşturuldu", "Termination Requested"),
        ["Act.İhlalBildirildi"] = ("İhlal Bildirildi", "Violation Reported"),
        ["Act.İhlalGiderildi"] = ("İhlal Giderildi", "Violation Resolved"),
        ["Act.Onaylandı"] = ("Onaylandı", "Approved"),
        ["Act.Reddedildi"] = ("Reddedildi", "Rejected"),
        ["Act.EkGörüntülendi"] = ("Ek Görüntülendi", "Attachment Viewed"),
        ["Act.Ekİndirildi"] = ("Ek İndirildi", "Attachment Downloaded"),
        ["Act.EkSilindi"] = ("Ek Silindi", "Attachment Deleted"),
        ["Act.SözleşmeYazdırıldı"] = ("Sözleşme Yazdırıldı", "Contract Printed"),
        ["Act.ListeDışaAktarıldı"] = ("Liste Excel'e Aktarıldı", "List Exported to Excel"),
        ["Act.KullanıcıOluşturuldu"] = ("Kullanıcı Oluşturuldu", "User Created"),
        ["Act.ŞifreSıfırlandı"] = ("Şifre Sıfırlandı (Yönetici)", "Password Reset (Admin)"),
        ["Act.ŞifreDeğiştirildi"] = ("Şifre Değiştirildi", "Password Changed"),
        ["Act.HesapDevreDışıBırakıldı"] = ("Hesap Devre Dışı Bırakıldı", "Account Disabled"),
        ["Act.HesapEtkinleştirildi"] = ("Hesap Etkinleştirildi", "Account Enabled"),
        ["Act.HesapKilitlendi"] = ("Hesap Kilitlendi", "Account Locked"),

        // --- Süreç adımları ---
        ["Step.RequestCreated"] = ("Talep oluşturuldu", "Request created"),
        ["Step.Approved"] = ("Onaylandı", "Approved"),
        ["Step.Rejected"] = ("Reddedildi", "Rejected"),
        ["Step.WithLog"] = ("{0} — {1}", "{0} — {1}"),
        ["Step.AwaitingFix"] = ("Düzeltme bekleniyor", "Awaiting correction"),
        ["Step.AwaitingContract"] = ("Sözleşme hazırlanmayı bekliyor (SYB)", "Awaiting contract preparation"),
        ["Step.AwaitingFinalCheck"] = ("SYB son kontrolü bekleniyor", "Awaiting final check"),
        ["Step.AwaitingManagement"] = ("Yönetim (YK) onayı bekleniyor", "Awaiting management approval"),
        ["Step.AwaitingApproval"] = ("Onay bekleniyor", "Awaiting approval"),
        ["Step.SuffixTermination"] = (" (fesih talebi)", " (termination request)"),
        ["Step.SuffixEdit"] = (" (düzenleme talebi)", " (amendment request)"),
        ["Step.InForce"] = ("Yürürlükte", "In force"),
        ["Step.InForceExpiring"] = ("Yürürlükte — bitiş tarihi yaklaşıyor", "In force — expiring soon"),
        ["Step.InForceViolation"] = ("Yürürlükte — ihlal bildirimi var", "In force — a violation has been reported"),
        ["Step.Completed"] = ("Süresi doldu — tamamlandı", "Expired — completed"),
        ["Step.Terminated"] = ("Feshedildi", "Terminated"),
        ["Step.RequestClosed"] = ("Talep reddedildi — kapatıldı", "Request rejected — closed"),
        ["Step.EditRejectedNote"] = ("Düzenleme talebi reddedildi; sözleşme değişiklik öncesi değerleriyle yürürlükte kaldı.",
                                     "The amendment was rejected; the contract stays in force with its previous values."),
        ["Step.TerminationRejectedNote"] = ("Fesih talebi reddedildi; sözleşme yürürlükte kalmaya devam ediyor.",
                                            "The termination was rejected; the contract remains in force."),

        // --- Ortak form ---
        ["Form.RequiredHint"] = ("Yıldızlı (*) alanlar zorunludur.", "Fields marked with * are required."),
        ["Form.Cancel"] = ("Vazgeç", "Cancel"),
        ["Form.CancelBack"] = ("← Vazgeç", "← Cancel"),
        ["Form.Summary"] = ("ÖZET", "SUMMARY"),
        ["Form.Remove"] = ("Kaldır", "Remove"),
        ["Form.Change"] = ("Değiştir", "Change"),
        ["Form.ChooseFile"] = ("Dosya Seç", "Choose File"),
        ["Form.File"] = ("Dosya", "File"),
        ["Form.NotSelected"] = ("Henüz seçilmedi", "Not selected yet"),

        // --- Yeni talep ---
        ["Req.RequestInfo"] = ("Talep Bilgileri", "Request Details"),
        ["Req.CompanyInfo"] = ("Firma Bilgileri", "Company Details"),
        ["Req.Subject"] = ("KONU / BAŞLIK", "SUBJECT / TITLE"),
        ["Req.SubjectShort"] = ("KONU", "SUBJECT"),
        ["Req.SubjectPlaceholder"] = ("Talebin kısa ve ayırt edici başlığı", "A short, distinctive title for the request"),
        ["Req.ContractType"] = ("SÖZLEŞME TÜRÜ", "CONTRACT TYPE"),
        ["Req.Reference"] = ("SAS / YK REFERANS NO", "SAS / BOARD REFERENCE NO"),
        ["Req.ReferencePlaceholder"] = ("Örn. 2026-0142", "e.g. 2026-0142"),
        ["Req.WorkDescription"] = ("İŞİN TANIMI", "SCOPE OF WORK"),
        ["Req.WorkPlaceholder"] = ("Talebin kapsamını, gerekçesini ve beklenen çıktıyı yazın.",
                                   "Describe the scope, the reason and the expected outcome."),
        ["Req.CompanyName"] = ("FİRMA ADI", "COMPANY NAME"),
        ["Req.CompanyHint"] = ("Sözleşmenin karşı tarafı.", "The counterparty to the contract."),
        ["Req.TaxNoPlaceholder"] = ("10 haneli", "10 digits"),
        ["Req.SapPlaceholder"] = ("C-XXXXX (yoksa boş bırakın)", "C-XXXXX (leave empty if none)"),
        ["Req.EstimatedAmount"] = ("TAHMİNİ BEDEL", "ESTIMATED AMOUNT"),
        ["Req.EstimatedHint"] = ("Yaklaşık bir tutar yeterli. Kesin bedel, sözleşme yaratılırken kalem kalem girilir.",
                                 "An approximate figure is enough. The exact amount is entered line by line when the contract is created."),
        ["Req.AttachmentHint"] = ("İsteğe bağlı — taslak, teklif veya şartname.", "Optional — a draft, quote or specification."),
        ["Req.FileTypes"] = ("PDF, Word, Excel veya görsel", "PDF, Word, Excel or image"),
        ["Req.AfterSubmit"] = ("GÖNDERDİKTEN SONRA", "AFTER YOU SUBMIT"),
        ["Req.Step1"] = ("SYB talebi inceler ve sözleşmeyi hazırlar.", "The contracts unit reviews the request and prepares the contract."),
        ["Req.Step2"] = ("SYB son kontrolü yapar.", "The contracts unit performs the final check."),
        ["Req.Step3"] = ("Yönetim (YK) onayıyla sözleşme yürürlüğe girer.", "Management approval brings the contract into force."),
        ["Req.NotifyHint"] = ("Her adımda bildirim alırsınız. Talep reddedilirse gerekçesi Sözleşmeler ekranında görünür.",
                              "You are notified at every step. If the request is rejected, the reason appears on the Contracts screen."),
        ["Req.EditNotice"] = ("Değişiklikleri kaydettiğinizde talep yeniden onaya gönderilir.",
                              "When you save your changes, the request is submitted for approval again."),
        ["Req.RenewalTitle"] = ("Sözleşme Yenileme", "Contract Renewal"),
        ["Req.RenewalNotice"] = ("Alanlar kaynak sözleşmeden dolduruldu. Kontrol edip değişenleri güncelleyin; kaynak sözleşme olduğu gibi kalır.",
                                 "The fields were filled from the source contract. Review and update what changed; the source contract is left untouched."),
        ["Req.SourceContract"] = ("Kaynak sözleşme:", "Source contract:"),
        ["Req.EndLabel"] = ("bitiş", "ends"),
        ["Req.AmountPlaceholder"] = ("0,00", "0,00"),

        // --- Sözleşme sihirbazı ---
        ["Wiz.Steps"] = ("ADIMLAR", "STEPS"),
        ["Wiz.Basics"] = ("Temel Bilgiler", "Basic Details"),
        ["Wiz.LineItems"] = ("Bedel Kalemleri", "Line Items"),
        ["Wiz.Documents"] = ("Belgeler", "Documents"),
        ["Wiz.PickRequest"] = ("SÖZLEŞMESİ OLUŞTURULACAK TALEP", "REQUEST TO TURN INTO A CONTRACT"),
        ["Wiz.NoPendingRequests"] = ("Bekleyen talep yok.", "No pending requests."),
        ["Wiz.Request"] = ("TALEP", "REQUEST"),
        ["Wiz.StartDate"] = ("BAŞLANGIÇ TARİHİ", "START DATE"),
        ["Wiz.EndDate"] = ("BİTİŞ TARİHİ", "END DATE"),
        ["Wiz.Currency"] = ("Para Birimi", "Currency"),
        ["Wiz.SapPlaceholder"] = ("C-XXXXX", "C-XXXXX"),
        ["Wiz.ItemsHint"] = ("Sözleşmenin toplam bedeli bu kalemlerden hesaplanır.",
                             "The contract total is calculated from these line items."),
        ["Wiz.ItemPlaceholder"] = ("Kalem tanımı", "Item description"),
        ["Wiz.AddItem"] = ("Kalem Ekle", "Add Item"),
        ["Wiz.DeleteItem"] = ("Kalemi sil", "Delete item"),
        ["Wiz.Definition"] = ("TANIM", "DESCRIPTION"),
        ["Wiz.Unit"] = ("BİRİM", "UNIT"),
        ["Wiz.Total"] = ("TOPLAM", "TOTAL"),
        ["Wiz.ContractFile"] = ("SÖZLEŞME DOSYASI", "CONTRACT FILE"),
        ["Wiz.ContractFileHint"] = ("Sözleşme metni, ekleri ve teminat belgeleri.",
                                    "The contract text, its annexes and guarantee documents."),
        ["Wiz.AddFile"] = ("+ Dosya Ekle", "+ Add File"),
        ["Wiz.NoFiles"] = ("Henüz dosya eklenmedi.", "No files added yet."),
        ["Wiz.Annexes"] = ("EKLER", "ANNEXES"),
        ["Wiz.Guarantee"] = ("TEMİNAT", "GUARANTEE"),
        ["Wiz.ExistingFiles"] = ("ZATEN EKLİ DOSYALAR", "FILES ALREADY ATTACHED"),
        ["Wiz.ExistingFilesHint"] = ("Bu dosyalar önceki denemede yüklendi ve sözleşmede kalmaya devam edecek. Aynı dosyayı tekrar eklemeyin.",
                                     "These files were uploaded in a previous attempt and will stay on the contract. Do not attach the same file again."),
        ["Wiz.Checklist"] = ("Kontrol Listesi", "Checklist"),
        ["Wiz.ChecklistNotice"] = ("Bu sözleşme Son Kontrol'e uğramadan doğrudan yönetim onayına gidecek; girdiğiniz bilgileri burada doğrulayın.",
                                   "This contract goes straight to management approval without a final check; verify the details you entered here."),
        ["Wiz.ChecklistRequired"] = ("Sözleşmeyi kaydetmek için tüm maddeleri işaretleyin.",
                                     "Tick every item before saving the contract."),
        ["Wiz.Save"] = ("Sözleşmeyi Kaydet", "Save Contract"),
        ["Wiz.Next"] = ("İleri →", "Next →"),
        ["Wiz.Back"] = ("← Geri", "← Back"),
        ["Wiz.BackToContracts"] = ("← Sözleşmeler", "← Contracts"),

        // --- Yeni talep: üretilen metinler ---
        ["Req.Submitting"] = ("Gönderiliyor...", "Submitting..."),
        ["Req.SaveAndResubmit"] = ("Kaydet ve Yeniden Gönder", "Save and Resubmit"),
        ["Req.SubmitRenewal"] = ("Yenileme Talebini Gönder", "Submit Renewal Request"),
        ["Req.SubmitForApproval"] = ("Onaya Gönder", "Submit for Approval"),
        ["Req.TitleRequired"] = ("Konu / başlık zorunludur.", "A subject / title is required."),
        ["Req.TypeRequired"] = ("Sözleşme türü seçilmelidir.", "A contract type must be selected."),
        ["Req.DescriptionRequired"] = ("İşin tanımı zorunludur.", "A scope of work is required."),
        ["Req.CompanyRequired"] = ("Firma adı zorunludur.", "A company name is required."),
        ["Req.TaxNoInvalid"] = ("Vergi no 10 haneli ve yalnızca rakamlardan oluşmalıdır.",
                                "The tax number must be exactly 10 digits."),
        ["Req.AmountInvalid"] = ("Geçerli bir tutar girin (örn. 12.500,00).", "Enter a valid amount (e.g. 12.500,00)."),
        ["Req.FixFields"] = ("Lütfen işaretli alanları düzeltin.", "Please correct the highlighted fields."),
        ["Req.UpdatedAndResent"] = ("Talep güncellendi ve yeniden gönderildi.", "The request was updated and resubmitted."),
        ["Req.Created"] = ("Talep başarıyla oluşturuldu.", "The request was created successfully."),

        // --- Sihirbaz: üretilen metinler ---
        ["Wiz.Step1Title"] = ("Temel Bilgiler", "Basic Details"),
        ["Wiz.Step1Sub"] = ("Talebi seçin, tarihleri ve ödeme koşullarını girin.",
                            "Select the request, then enter dates and payment terms."),
        ["Wiz.Step2Title"] = ("Bedel Kalemleri", "Line Items"),
        ["Wiz.Step2Sub"] = ("Sözleşmenin tutarı kalem kalem burada oluşur.",
                            "The contract total is built up line by line here."),
        ["Wiz.Step3Title"] = ("Belgeler ve Gönder", "Documents and Submit"),
        ["Wiz.Step3Sub"] = ("Dosyaları ekleyip sözleşmeyi onaya gönderin.",
                            "Attach the files and submit the contract for approval."),
        ["Wiz.ChecklistProgress"] = ("{0} / {1} madde", "{0} of {1} items"),
        ["Wiz.LoadRequestsFailed"] = ("Talepler yüklenirken bir hata oluştu: {0}",
                                      "An error occurred while loading requests: {0}"),
        ["Wiz.LoadPreviousFailed"] = ("Talebin önceki verileri yüklenemedi: {0}",
                                      "The request's previous data could not be loaded: {0}"),
        ["Wiz.RecreateNotice"] = ("Bu talep için daha önce sözleşme oluşturulmuş. Önceki kalemler ve tarihler forma yüklendi; kaydettiğinizde kalemler bu listeyle DEĞİŞTİRİLİR.",
                                  "A contract was created from this request before. The previous line items and dates were loaded into the form; saving REPLACES the line items with this list."),
        ["Wiz.RenewalNotice"] = ("Bu bir yenileme talebi. Kalemler {0} numaralı önceki sözleşmeden yüklendi — birim fiyatları ve miktarları yeni döneme göre kontrol edin. Tarihler kasıtlı olarak boş bırakıldı.",
                                 "This is a renewal request. The line items were loaded from contract {0} — check unit prices and quantities for the new period. The dates were deliberately left empty."),
        ["Wiz.RequestRequired"] = ("Bir talep seçilmelidir.", "A request must be selected."),
        ["Wiz.StartRequired"] = ("Başlangıç tarihi zorunludur.", "A start date is required."),
        ["Wiz.EndRequired"] = ("Bitiş tarihi zorunludur.", "An end date is required."),
        ["Wiz.EndBeforeStart"] = ("Bitiş tarihi, başlangıç tarihinden sonra olmalıdır.",
                                  "The end date must be later than the start date."),
        ["Wiz.PaymentRequired"] = ("Ödeme periyodu seçilmelidir.", "A payment period must be selected."),
        ["Wiz.FixFields"] = ("Lütfen işaretli alanları düzeltin.", "Please correct the highlighted fields."),
        ["Wiz.AtLeastOneItem"] = ("Lütfen en az bir kalem ekleyin.", "Please add at least one line item."),
        ["Wiz.ItemDescriptionRequired"] = ("Lütfen tüm kalemlerin açıklamasını doldurun.",
                                           "Please fill in a description for every line item."),
        ["Wiz.QuantityPositive"] = ("Kalem miktarı 0'dan büyük olmalı.", "The quantity must be greater than 0."),
        ["Wiz.NoRequestSelected"] = ("Talep seçilmedi.", "No request selected."),
        ["Wiz.ChecklistIncomplete"] = ("Göndermeden önce kontrol listesindeki tüm maddeleri işaretleyin.",
                                       "Tick every checklist item before submitting."),
        ["Wiz.Created"] = ("Sözleşme başarıyla oluşturuldu. Sol menüden 'Sözleşmeler'e bakarak kontrol edebilirsiniz.",
                           "The contract was created successfully. You can check it under 'Contracts' in the menu."),

        // --- Dosya seçici pencereleri ---
        ["File.ChooseFile"] = ("Dosya Seç", "Choose File"),
        ["File.Supported"] = ("Desteklenen Dosyalar", "Supported Files"),
        ["File.SaveAs"] = ("Dosyayı Kaydet", "Save File"),
        ["File.SaveExcel"] = ("Excel Olarak Kaydet", "Save as Excel"),
        ["File.ExcelWorkbook"] = ("Excel Çalışma Kitabı", "Excel Workbook"),
        ["File.SavePdf"] = ("PDF Olarak Kaydet", "Save as PDF"),
        ["File.PdfDocument"] = ("PDF Belgesi", "PDF Document"),
        ["File.PdfFiles"] = ("PDF Dosyaları", "PDF Files"),
        ["File.ChooseTermination"] = ("Fesih Belgesi Seç", "Choose Termination Document"),
        ["File.PickFailed"] = ("Dosya seçilirken bir hata oluştu: {0}", "An error occurred while choosing the file: {0}"),
        ["File.ExportFailed"] = ("Excel'e aktarılırken bir hata oluştu: {0}",
                                 "An error occurred while exporting to Excel: {0}"),
        ["File.PdfFailed"] = ("PDF oluşturulurken bir hata oluştu: {0}", "An error occurred while creating the PDF: {0}"),
        ["File.DownloadFailed"] = ("Dosya indirilirken bir hata oluştu: {0}",
                                   "An error occurred while downloading the file: {0}"),

        // --- Ortak hata kalıpları ---
        ["Err.ContractsLoadFailed"] = ("Sözleşmeler yüklenirken bir hata oluştu: {0}",
                                       "An error occurred while loading contracts: {0}"),
        ["Err.Prefix"] = ("Hata: {0}", "Error: {0}"),
        ["Err.FixFields"] = ("Lütfen işaretli alanları düzeltin.", "Please correct the highlighted fields."),
        ["Err.ContractRequired"] = ("Bir sözleşme seçilmelidir.", "A contract must be selected."),
        ["Err.ApproveFailed"] = ("Onay işlemi sırasında bir hata oluştu: {0}",
                                 "An error occurred during approval: {0}"),
        ["Err.RejectFailed"] = ("Red işlemi sırasında bir hata oluştu: {0}",
                                "An error occurred during rejection: {0}"),

        // --- Sözleşme detayı ---
        ["Det.RenewalOfWithEnd"] = ("{0} numaralı sözleşmenin yenilemesidir (önceki dönem {1} tarihinde sona erdi).",
                                    "This is a renewal of contract {0} (the previous period ended on {1})."),
        ["Det.RenewalOf"] = ("{0} numaralı sözleşmenin yenilemesidir.", "This is a renewal of contract {0}."),
        ["Det.NoAccess"] = ("Bu sözleşmeyi görüntüleme yetkiniz yok.", "You are not authorised to view this contract."),
        ["Det.DetailLoadFailed"] = ("Sözleşme detayı yüklenirken bir hata oluştu: {0}",
                                    "An error occurred while loading the contract details: {0}"),
        ["Det.ViolationResolveFailed"] = ("İhlal giderildi olarak işaretlenemedi: {0}",
                                          "The violation could not be marked as resolved: {0}"),
        ["Det.ViolationFailed"] = ("İhlal işlenirken bir hata oluştu: {0}", "An error occurred while processing the violation: {0}"),
        ["Det.DeleteFailed"] = ("Silme işlemi sırasında bir hata oluştu: {0}", "An error occurred while deleting: {0}"),
        ["Det.PrintFailed"] = ("Yazdırma başlatılamadı: {0}", "Printing could not be started: {0}"),
        ["Det.FileOpenFailed"] = ("Dosya açılamadı: {0}", "The file could not be opened: {0}"),
        ["Det.PdfFailed"] = ("PDF oluşturulamadı: {0}", "The PDF could not be created: {0}"),

        // --- Sözleşme değiştir ---
        ["Edit.NewAmount"] = ("Yeni Bedel", "New Amount"),
        ["Edit.NewAmountWithCurrency"] = ("YENİ BEDEL ({0})", "NEW AMOUNT ({0})"),
        ["Edit.ReasonRequired"] = ("Değişiklik gerekçesi zorunludur.", "A reason for the amendment is required."),
        ["Edit.AmountInvalid"] = ("Yeni bedel geçerli, negatif olmayan bir sayı olmalı.",
                                  "The new amount must be a valid, non-negative number."),
        ["Edit.Submitted"] = ("Değişiklik talebi gönderildi. Sözleşme yeniden onay sürecine alındı.",
                              "The amendment request was submitted. The contract has re-entered the approval process."),

        // --- Fesih ---
        ["Term.Compensation"] = ("Fesih Tazminatı", "Termination Compensation"),
        ["Term.CompensationWithCurrency"] = ("FESİH TAZMİNATI ({0})", "TERMINATION COMPENSATION ({0})"),
        ["Term.Ended"] = ("Sona erdi", "Ended"),
        ["Term.ReasonRequired"] = ("Fesih gerekçesi zorunludur.", "A reason for termination is required."),
        ["Term.DateRequired"] = ("Fesih tarihi zorunludur.", "A termination date is required."),
        ["Term.DateBeforeStart"] = ("Fesih tarihi, sözleşme başlangıcından ({0}) önce olamaz.",
                                    "The termination date cannot be earlier than the contract start ({0})."),
        ["Term.DateAfterEnd"] = ("Fesih tarihi, sözleşme bitişinden ({0}) sonra olamaz; sözleşme o tarihte zaten sona eriyor.",
                                 "The termination date cannot be later than the contract end ({0}); the contract already ends then."),
        ["Term.FileRequired"] = ("Fesih bildirimi / tutanak (PDF) zorunludur.",
                                 "A termination notice or minutes (PDF) is required."),
        ["Term.AmountInvalid"] = ("Tazminat tutarı geçerli, negatif olmayan bir sayı olmalı.",
                                  "The compensation amount must be a valid, non-negative number."),
        ["Term.AmountRequiredWithDirection"] = ("Tazminat yönü seçildiğinde tutar girilmelidir.",
                                                "An amount must be entered when a compensation direction is chosen."),
        ["Term.Submitted"] = ("Fesih talebi gönderildi. SYB son kontrolü ve ardından Müdür onayı bekleniyor.",
                              "The termination request was submitted. It now awaits the final check and then management approval."),
        ["Term.SubmitFailed"] = ("Fesih talebi gönderilirken bir hata oluştu: {0}",
                                 "An error occurred while submitting the termination request: {0}"),

        // --- İhlal bildirimi ---
        ["Vio.HistoryLoadFailed"] = ("Sözleşmenin ihlal geçmişi yüklenemedi: {0}",
                                     "The contract's violation history could not be loaded: {0}"),
        ["Vio.DescriptionRequired"] = ("Açıklama zorunludur.", "A description is required."),
        ["Vio.DateRequired"] = ("İhlal tarihi zorunludur.", "A violation date is required."),
        ["Vio.DateInFuture"] = ("İhlal tarihi gelecekte olamaz.", "The violation date cannot be in the future."),
        ["Vio.DateBeforeStart"] = ("İhlal tarihi, sözleşme başlangıcından ({0}) önce olamaz.",
                                   "The violation date cannot be earlier than the contract start ({0})."),
        ["Vio.Saved"] = ("İhlal bildirimi kaydedildi. Sözleşme \"İhlal Mevcut\" durumuna geçti ve SYB'ye bildirim gönderildi.",
                         "The violation was recorded. The contract moved to \"In Violation\" and the contracts unit was notified."),
        ["Vio.ReportFailed"] = ("İhlal bildirilirken bir hata oluştu: {0}",
                                "An error occurred while reporting the violation: {0}"),
        ["Vio.ResolveLastOpen"] = ("Bu sözleşmenin son açık ihlali. İşaretlediğinizde sözleşme \"{0}\" durumuna dönecek.",
                                   "This is the contract's last open violation. Marking it returns the contract to \"{0}\"."),
        ["Vio.ResolveMoreOpen"] = ("Sözleşmede başka açık ihlaller var; durumu \"İhlal Mevcut\" olarak kalmaya devam edecek.",
                                   "The contract has other open violations; it stays \"In Violation\"."),
        ["Vio.ResolveAsk"] = ("\"{0}\" ihlali giderildi olarak işaretlenecek.", "The violation \"{0}\" will be marked as resolved."),
        ["Vio.ResolveTitle"] = ("İhlali Gider", "Resolve Violation"),
        ["Vio.ResolveQuestion"] = ("İhlal nasıl giderildi?", "How was the violation resolved?"),
        ["Vio.ResolvePlaceholder"] = ("Eksik iş tamamlandı, gecikme telafi edildi, tutanak imzalandı...",
                                      "The outstanding work was completed, the delay was made up, minutes were signed..."),
        ["Vio.ResolveConfirm"] = ("Giderildi Olarak İşaretle", "Mark as Resolved"),
        ["Vio.ResolutionRequired"] = ("İhlalin nasıl giderildiği yazılmalıdır.",
                                      "You must describe how the violation was resolved."),

        // --- Kullanıcı yönetimi ---
        ["Usr.NoDepartment"] = ("Departman belirtilmemiş", "No department set"),
        ["Usr.Disabled"] = ("Devre Dışı", "Disabled"),
        ["Usr.Active"] = ("Aktif", "Active"),
        ["Usr.Enable"] = ("Etkinleştir", "Enable"),
        ["Usr.Disable"] = ("Devre Dışı Bırak", "Disable"),
        ["Usr.NotFound"] = ("\"{0}\" — bu kullanıcı adı sistemde bulunamadı",
                            "\"{0}\" — this username was not found"),
        ["Usr.AllRoles"] = ("Tüm roller", "All roles"),
        ["Usr.PendingResets"] = ("Bekleyen Şifre Sıfırlama Talepleri ({0})", "Pending Password Reset Requests ({0})"),
        ["Usr.LoadFailed"] = ("Kullanıcılar yüklenirken bir hata oluştu: {0}",
                              "An error occurred while loading users: {0}"),
        ["Usr.FieldsRequired"] = ("Kullanıcı adı, ad soyad ve şifre zorunludur.",
                                  "Username, full name and password are required."),
        ["Usr.FirstLoginNotice"] = ("Kullanıcı ilk girişinde kendi şifresini belirleyecek.",
                                    "The user will set their own password at first sign-in."),

        // --- Geçmiş satırları ---
        ["Hist.AwaitingResult"] = ("Sonuç bekliyor", "Awaiting result"),
        ["Hist.PreviousAmount"] = ("Önceki bedel: ", "Previous amount: "),
        ["Hist.PreviousEnd"] = ("Önceki bitiş: ", "Previous end date: "),
        ["Hist.PreviousCompany"] = ("Önceki firma: ", "Previous company: "),
        ["Hist.PreviousPayment"] = ("Önceki ödeme koşulu: ", "Previous payment terms: "),
        ["Hist.ViolationDate"] = ("İhlal tarihi: ", "Violation date: "),
        ["Hist.Resolved"] = ("Giderildi ({0}): {1}", "Resolved ({0}): {1}"),
        ["Hist.TerminationDate"] = ("Fesih tarihi: ", "Termination date: "),
        ["Hist.Compensation"] = ("Tazminat: ", "Compensation: "),

        // --- Diğer ---
        ["Notif.JustNow"] = ("az önce", "just now"),
        ["Shell.NotificationsWithCount"] = ("Bildirimler · {0} okunmamış", "Notifications · {0} unread"),
        ["Wiz.SapRequired"] = ("SAP cari kodu zorunludur.", "A SAP account code is required."),
        ["Wiz.UnitPriceNegative"] = ("Birim fiyat negatif olamaz.", "The unit price cannot be negative."),
        ["Req.TaxNoRequired"] = ("Vergi no zorunludur.", "A tax number is required."),
        ["Req.AmountNegative"] = ("Tutar negatif olamaz.", "The amount cannot be negative."),

        // --- Talep reddi / geri çekme diyaloğu ---
        ["Rjd.HeaderWithdraw"] = ("\"{0}\" talebiniz geri çekilecek.", "Your request \"{0}\" will be withdrawn."),
        ["Rjd.HeaderReject"] = ("\"{0}\" talebi reddedilecek.", "The request \"{0}\" will be rejected."),
        ["Rjd.Reason"] = ("Gerekçe", "Reason"),
        ["Rjd.RejectReason"] = ("Red gerekçesi", "Reason for rejection"),
        ["Rjd.WithdrawHint"] = ("Talebi neden geri çektiğinizi yazın. İşlem geçmişine kaydedilir.",
                                "Say why you are withdrawing the request. It is written to the audit log."),
        ["Rjd.RejectHint"] = ("Talebin neden reddedildiğini yazın. Bu metin talep sahibine bildirim olarak iletilir.",
                              "Say why the request is rejected. This text is sent to the requester as a notification."),
        ["Rjd.ResubmitOwn"] = ("Düzeltip yeniden göndereceğim", "I will correct it and resubmit"),
        ["Rjd.ResubmitOther"] = ("Düzeltilip yeniden gönderilebilir", "Can be corrected and resubmitted"),
        ["Rjd.Withdraw"] = ("Geri Çek", "Withdraw"),
        ["Rjd.Close"] = ("Kapat", "Close"),
        ["Rjd.Return"] = ("İade Et", "Return"),
        ["Rjd.RejectAndClose"] = ("Reddet ve Kapat", "Reject and Close"),
        ["Rjd.HintStaysEditable"] = ("Talep düzenlenebilir durumda kalır; düzeltip yeniden gönderebilirsiniz.",
                                     "The request stays editable; you can correct it and resubmit."),
        ["Rjd.HintReturns"] = ("Talep sahibine geri döner; düzeltip yeniden gönderebilir.",
                               "It goes back to the requester, who can correct it and resubmit."),
        ["Rjd.HintFinal"] = ("Talep nihai olarak kapanır ve yeniden gönderilemez.",
                             "The request is closed for good and cannot be resubmitted."),
        ["Rjd.ReasonRequired"] = ("Red gerekçesi zorunludur.", "A reason is required."),

        // --- Sözleşme detayı ekranı ---
        ["Det.PickerPlaceholder"] = ("Listeden bir sözleşme seçin...", "Select a contract from the list..."),
        ["Det.SearchWatermark"] = ("Ara: no, başlık, firma", "Search: number, title, company"),
        ["Det.ViewedContract"] = ("GÖRÜNTÜLENEN SÖZLEŞME", "CONTRACT SHOWN"),
        ["Det.PickFromAbove"] = ("Görüntülemek istediğiniz sözleşmeyi yukarıdan seçin.",
                                 "Choose the contract you want to view from above."),
        ["Det.DaysLeft"] = ("KALAN GÜN", "DAYS LEFT"),
        ["Det.RevisionHistory"] = ("Revizyon Geçmişi", "Amendment History"),
        ["Det.ViolationHistory"] = ("İhlal Geçmişi", "Violation History"),
        ["Det.TerminationHistory"] = ("Fesih Geçmişi", "Termination History"),
        ["Det.MarkResolved"] = ("Giderildi olarak işaretle", "Mark as resolved"),
        ["Det.Download"] = ("İndir", "Download"),
        ["Det.Delete"] = ("Sil", "Delete"),
        ["Det.Back"] = ("← Geri", "← Back"),

        // --- Sözleşme değiştir ekranı ---
        ["Edit.PickerPlaceholder"] = ("Değiştirilecek sözleşmeyi seçin...", "Select the contract to amend..."),
        ["Edit.NoEligible"] = ("Değiştirilebilecek uygun sözleşme yok.", "There are no contracts eligible for amendment."),
        ["Edit.PickFromLeft"] = ("Soldan bir sözleşme seçin.", "Select a contract on the left."),
        ["Edit.TypeSection"] = ("Sözleşme ve Değişiklik Türü", "Contract and Amendment Type"),
        ["Edit.CurrentContract"] = ("MEVCUT SÖZLEŞME", "CURRENT CONTRACT"),
        ["Edit.Contract"] = ("SÖZLEŞME", "CONTRACT"),
        ["Edit.WhatChanges"] = ("NE DEĞİŞİYOR?", "WHAT IS CHANGING?"),
        ["Edit.Reason"] = ("DEĞİŞİKLİK GEREKÇESİ", "REASON FOR AMENDMENT"),
        ["Edit.ReasonPlaceholder"] = ("Neden bu değişikliğe ihtiyaç var? Onaycılar bu metni okuyacak.",
                                      "Why is this change needed? Approvers will read this text."),
        ["Edit.NewValues"] = ("Yeni Değerler", "New Values"),
        ["Edit.OnlyChangedHint"] = ("Yalnızca değişen alanları doldurun; boş bıraktıklarınız aynı kalır.",
                                    "Fill in only the fields that change; anything left empty stays as it is."),
        ["Edit.Current"] = ("Mevcut: ", "Current: "),
        ["Edit.NewEndDate"] = ("YENİ BİTİŞ TARİHİ", "NEW END DATE"),
        ["Edit.NewScope"] = ("YENİ KAPSAM / İŞ TANIMI", "NEW SCOPE OF WORK"),
        ["Edit.NewCompany"] = ("YENİ FİRMA ADI", "NEW COMPANY NAME"),
        ["Edit.NewTaxNo"] = ("YENİ VERGİ NO", "NEW TAX NO"),
        ["Edit.NewPaymentTerms"] = ("YENİ ÖDEME KOŞULLARI", "NEW PAYMENT TERMS"),
        ["Edit.PaymentTerms"] = ("ÖDEME KOŞULLARI", "PAYMENT TERMS"),
        ["Edit.SupportingDoc"] = ("Ek Belge", "Supporting Document"),
        ["Edit.SupportingHint"] = ("İsteğe bağlı — zeyilname, yazışma veya destekleyici belge.",
                                   "Optional — an addendum, correspondence or supporting document."),
        ["Edit.GoesToApproval"] = ("Değişiklik yeniden onaya gider", "The amendment goes back through approval"),
        ["Edit.ApprovalNotice"] = ("Sözleşme, SYB Son Kontrol ve Yönetim (YK) onayından geçene kadar mevcut haliyle yürürlükte kalır. Önceki değerler revizyon geçmişine kaydedilir.",
                                   "The contract stays in force as it is until the final check and management approval are complete. The previous values are written to the amendment history."),
        ["Edit.Submit"] = ("Değişiklik Talebini Gönder", "Submit Amendment Request"),

        // --- Fesih ekranı ---
        ["Term.PickerPlaceholder"] = ("Sözleşme seçin...", "Select a contract..."),
        ["Term.NoEligible"] = ("Feshedilebilecek uygun sözleşme yok.", "There are no contracts eligible for termination."),
        ["Term.PickFromLeft"] = ("Soldan bir sözleşme seçin.", "Select a contract on the left."),
        ["Term.TypeSection"] = ("Sözleşme ve Fesih Türü", "Contract and Termination Type"),
        ["Term.ContractToTerminate"] = ("FESHEDİLECEK SÖZLEŞME", "CONTRACT TO TERMINATE"),
        ["Term.Type"] = ("FESİH TÜRÜ", "TERMINATION TYPE"),
        ["Term.Date"] = ("FESİH TARİHİ", "TERMINATION DATE"),
        ["Term.Reason"] = ("FESİH GEREKÇESİ", "REASON FOR TERMINATION"),
        ["Term.ReasonPlaceholder"] = ("Feshin gerekçesini detaylı açıklayın.", "Explain the reason for termination in detail."),
        ["Term.ReasonHint"] = ("Bu metin hukuki kayıt niteliği taşır ve onaycıların gördüğü tek gerekçedir.",
                               "This text is a legal record and is the only reason approvers see."),
        ["Term.RemainingTime"] = ("KALAN SÜRE", "TIME REMAINING"),
        ["Term.JustCauseHint"] = ("\"Haklı Fesih\" ihlale dayanır. Sistemde kayıt yoksa önce İhlal Bildir ekranından ihlali kaydedin ya da gerekçede dayanağı (yazışma, tutanak) açıkça belirtin.",
                                  "\"Termination for cause\" rests on a violation. If none is recorded, report the violation first or state the evidence (correspondence, minutes) explicitly in the reason."),
        ["Term.NoRecordedViolation"] = ("Bu sözleşmede kayıtlı ihlal yok", "No violation is recorded for this contract"),
        ["Term.Direction"] = ("TAZMİNAT YÖNÜ", "COMPENSATION DIRECTION"),
        ["Term.CompensationSection"] = ("Tazminat", "Compensation"),
        ["Term.DirectionHint"] = ("Tazminat yoksa yönü \"Tazminat yok\" bırakın ve tutarı boş geçin.",
                                  "If there is no compensation, leave the direction as \"No compensation\" and the amount empty."),
        ["Term.AmountHint"] = ("Tazminat yönü seçilince açılır.", "Enabled once a compensation direction is chosen."),
        ["Term.Document"] = ("Fesih Bildirimi / Tutanak", "Termination Notice / Minutes"),
        ["Term.DocumentHint"] = ("Zorunlu — yalnızca PDF.", "Required — PDF only."),
        ["Term.ChoosePdf"] = ("PDF Seç", "Choose PDF"),
        ["Term.EndsContract"] = ("Fesih, sözleşmeyi sonlandırır", "Termination ends the contract"),
        ["Term.ApprovalNotice"] = ("Talep önce SYB son kontrolünden, ardından Yönetim (YK) onayından geçer. Onaylanana kadar sözleşme yürürlükte kalır; onaylandığında feshedilir ve arşive alınır.",
                                   "The request passes the final check first, then management approval. The contract stays in force until approved; once approved it is terminated and archived."),
        ["Term.Submit"] = ("Fesih Talebini Gönder", "Submit Termination Request"),

        // --- İhlal bildir ekranı ---
        ["Vio.PickerPlaceholder"] = ("Sözleşme seçin...", "Select a contract..."),
        ["Vio.NoEligible"] = ("İhlal bildirilebilecek uygun sözleşme yok.",
                              "There are no contracts eligible for a violation report."),
        ["Vio.PickFromLeft"] = ("Soldan bir sözleşme seçin.", "Select a contract on the left."),
        ["Vio.Section"] = ("Sözleşme ve İhlal", "Contract and Violation"),
        ["Vio.RelatedContract"] = ("İLGİLİ SÖZLEŞME", "RELATED CONTRACT"),
        ["Vio.Type"] = ("İHLAL TÜRÜ", "VIOLATION TYPE"),
        ["Vio.Date"] = ("İHLAL TARİHİ", "VIOLATION DATE"),
        ["Vio.Description"] = ("AÇIKLAMA", "DESCRIPTION"),
        ["Vio.DescriptionPlaceholder"] = ("İhlalin ayrıntılı açıklaması, belge referansları, kanıtlar...",
                                          "A detailed description, document references, evidence..."),
        ["Vio.DescriptionHint"] = ("Bu metin sözleşme geçmişinde kalıcı olarak saklanır ve fesih kararına dayanak oluşturabilir.",
                                   "This text is kept permanently in the contract history and may support a termination decision."),
        ["Vio.PreviousViolations"] = ("ÖNCEKİ İHLALLER", "PREVIOUS VIOLATIONS"),
        ["Vio.SupportingDoc"] = ("Destekleyici Belge", "Supporting Document"),
        ["Vio.SupportingHint"] = ("İsteğe bağlı — yazışma, tutanak, fotoğraf veya rapor.",
                                  "Optional — correspondence, minutes, a photo or a report."),
        ["Vio.NoApprovalNeeded"] = ("İhlal bildirimi onaya gitmez, anında geçerli olur",
                                    "A violation report needs no approval; it takes effect immediately"),
        ["Vio.EffectNotice"] = ("Kaydettiğinizde sözleşme \"İhlal Mevcut\" durumuna geçer ve SYB'ye bildirim gönderilir. Kayıt sözleşmenin geçmişinde kalıcıdır.",
                                "When you save, the contract moves to \"In Violation\" and the contracts unit is notified. The record stays permanently in the contract's history."),
        ["Vio.Submit"] = ("İhlali Bildir", "Report Violation"),

        // --- Kullanıcı yönetimi ekranı ---
        ["Usr.SearchPlaceholder"] = ("Ad, kullanıcı adı veya departman...", "Name, username or department..."),
        ["Usr.Search"] = ("ARA", "SEARCH"),
        ["Usr.Role"] = ("ROL", "ROLE"),
        ["Usr.Status"] = ("DURUM", "STATUS"),
        ["Usr.NoMatch"] = ("Bu filtrelerle eşleşen kullanıcı bulunamadı.", "No users match these filters."),
        ["Usr.NewUser"] = ("Yeni Kullanıcı", "New User"),
        ["Usr.Create"] = ("Kullanıcı Oluştur", "Create User"),
        ["Usr.FullName"] = ("AD SOYAD", "FULL NAME"),
        ["Usr.Username"] = ("KULLANICI ADI", "USERNAME"),
        ["Usr.Department"] = ("DEPARTMAN", "DEPARTMENT"),
        ["Usr.TempPassword"] = ("GEÇİCİ ŞİFRE", "TEMPORARY PASSWORD"),
        ["Usr.PasswordPlaceholder"] = ("En az 8 karakter, harf ve rakam", "At least 8 characters, letters and digits"),
        ["Usr.Optional"] = ("Opsiyonel", "Optional"),
        ["Usr.ResetPassword"] = ("Şifre Sıfırla", "Reset Password"),
        ["Usr.SetNewPassword"] = ("Yeni şifre belirle", "Set a new password"),
        ["Usr.Save"] = ("Kaydet", "Save"),
        ["Usr.Close"] = ("Kapat", "Close"),
        ["Usr.You"] = ("siz", "you"),
        ["Usr.CloseRequestHint"] = ("Talebi karşılamadan kapat", "Close without fulfilling the request"),
        ["Usr.ResetHint"] = ("Şifreyi sıfırlamak için ilgili kullanıcının satırındaki \"Şifre Sıfırla\" butonunu kullanın; talep otomatik kapanır.",
                             "Use the \"Reset Password\" button on that user's row; the request closes automatically."),
        ["Usr.RequiredHint"] = ("Yıldızlı (*) alanlar zorunludur. Kullanıcı ilk girişinde şifresini değiştirmelidir.",
                                "Fields marked with * are required. The user must change their password at first sign-in."),

        // --- Çıktı (PDF / yazdırma) ---
        //
        // Künye, kullanıcının o an seçtiği dilde üretilir. Etiketler çevrilir;
        // sözleşmenin KENDİ verisi (tür, ödeme periyodu, firma türü, adım adı,
        // gerekçe metinleri) çevrilmez — ekrandaki kuralın aynısı.
        ["Out.Title"] = ("SÖZLEŞME KÜNYESİ", "CONTRACT SUMMARY"),
        ["Out.DocTitle"] = ("Sözleşme Künyesi", "Contract Summary"),
        ["Out.Contract"] = ("Sözleşme", "Contract"),
        ["Out.AppName"] = ("SYS — Sözleşme Yönetim Sistemi", "SYS — Contract Management System"),
        ["Out.Created"] = ("Oluşturma: {0}", "Generated: {0}"),
        ["Out.ContractNo"] = ("Sözleşme No", "Contract No"),
        ["Out.RequestRefNo"] = ("Talep Referans No", "Request Ref. No"),
        ["Out.Status"] = ("Durum", "Status"),
        ["Out.Type"] = ("Tür", "Type"),
        ["Out.Company"] = ("Firma", "Company"),
        ["Out.TaxNo"] = ("Vergi No", "Tax No"),
        ["Out.SapCode"] = ("SAP Cari Kodu", "SAP Account Code"),
        ["Out.Requester"] = ("Talep Eden", "Requested By"),
        ["Out.StartDate"] = ("Başlangıç Tarihi", "Start Date"),
        ["Out.EndDate"] = ("Bitiş Tarihi", "End Date"),
        ["Out.PaymentPeriod"] = ("Ödeme Periyodu", "Payment Period"),
        ["Out.TotalAmount"] = ("Toplam Bedel", "Total Amount"),
        ["Out.Scope"] = ("Kapsam", "Scope"),
        ["Out.Items"] = ("Kalemler", "Line Items"),
        ["Out.ColDescription"] = ("AÇIKLAMA", "DESCRIPTION"),
        ["Out.ColQuantity"] = ("MİKTAR", "QUANTITY"),
        ["Out.ColUnitPrice"] = ("BİRİM FİYAT", "UNIT PRICE"),
        ["Out.ColAmount"] = ("TUTAR", "AMOUNT"),
        ["Out.Total"] = ("Toplam", "Total"),
        ["Out.ProcessSteps"] = ("Süreç Adımları", "Process Steps"),
        ["Out.ViolationHistory"] = ("İhlal Geçmişi", "Violation History"),
        ["Out.RevisionHistory"] = ("Revizyon Geçmişi", "Amendment History"),
        ["Out.TerminationHistory"] = ("Fesih Geçmişi", "Termination History"),
        ["Out.ViolationDate"] = ("İhlal tarihi: {0}", "Violation date: {0}"),
        ["Out.ViolationResolved"] = ("Giderildi ({0}): {1}", "Resolved ({0}): {1}"),
        ["Out.ViolationOpen"] = ("Açık", "Open"),
        ["Out.ViolationResolvedShort"] = ("Giderildi", "Resolved"),
        ["Out.PreviousAmount"] = ("Önceki bedel: {0}", "Previous amount: {0}"),
        ["Out.PreviousEnd"] = (" · Önceki bitiş: {0}", " · Previous end date: {0}"),
        ["Out.TerminationDate"] = ("Fesih tarihi: {0}", "Termination date: {0}"),
        ["Out.Compensation"] = (" · Tazminat: {0} ({1})", " · Compensation: {0} ({1})"),
        ["Out.Approved"] = ("Onaylandı", "Approved"),
        ["Out.Rejected"] = ("Reddedildi", "Rejected"),
        ["Out.AwaitingResult"] = ("Sonuç bekliyor", "Awaiting result"),
        ["Out.PageOf"] = ("Sayfa {0} / {1}", "Page {0} of {1}"),

        // --- Excel sütun başlıkları ---
        ["Xls.ContractNo"] = ("Sözleşme No", "Contract No"),
        ["Xls.RequestRef"] = ("Talep Ref No", "Request Ref No"),
        ["Xls.Title"] = ("Başlık", "Title"),
        ["Xls.Company"] = ("Firma", "Company"),
        ["Xls.TaxNo"] = ("Vergi No", "Tax No"),
        ["Xls.SapCode"] = ("SAP Cari Kodu", "SAP Account Code"),
        ["Xls.Type"] = ("Tür", "Type"),
        ["Xls.CompanyType"] = ("Firma Türü", "Company Type"),
        ["Xls.Status"] = ("Durum", "Status"),
        ["Xls.Start"] = ("Başlangıç", "Start"),
        ["Xls.End"] = ("Bitiş", "End"),
        ["Xls.DaysLeft"] = ("Kalan Gün", "Days Left"),
        ["Xls.Amount"] = ("Bedel", "Amount"),
        ["Xls.Currency"] = ("Para Birimi", "Currency"),
        ["Xls.PaymentPeriod"] = ("Ödeme Periyodu", "Payment Period"),
        ["Xls.Requester"] = ("Talep Eden", "Requested By"),
        ["Xls.Department"] = ("Departman", "Department"),
        ["Xls.CreatedAt"] = ("Oluşturma", "Created"),
        ["Xls.Date"] = ("Tarih", "Date"),
        ["Xls.User"] = ("Kullanıcı", "User"),
        ["Xls.Action"] = ("İşlem", "Action"),
        ["Xls.EntityType"] = ("Kayıt Türü", "Record Type"),
        ["Xls.EntityId"] = ("Kayıt No", "Record No"),
        ["Xls.Detail"] = ("Ayrıntı", "Detail"),

        // --- Roller ---
        ["Role.Personel"] = ("Personel", "Employee"),
        ["Role.Syb"] = ("SYB Uzmanı", "Contracts Specialist"),
        ["Role.Mudur"] = ("Yönetim / Mali İşler", "Management / Finance"),
        ["Role.Admin"] = ("Sistem Yöneticisi", "System Administrator"),
    };
}
